from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlmodel import Column, Field, SQLModel, Text


class Listing(SQLModel, table=True):
    """
    Persistent record of every ad generated by a user.
    Stores all data needed to reconstruct the listing for Facebook,
    display history, and check sold status.
    """
    __tablename__ = "listings"

    id:               int = Field(default=None, primary_key=True)
    user_id:          int = Field(foreign_key="users.id", index=True)
    job_id:           Optional[int] = Field(default=None, foreign_key="jobs.id")

    # Vehicle data
    vin:              Optional[str] = Field(default=None, max_length=17)
    year:             Optional[str] = Field(default=None, max_length=4)
    make:             Optional[str] = Field(default=None, max_length=100)
    model:            Optional[str] = Field(default=None, max_length=100)
    trim:             Optional[str] = Field(default=None, max_length=100)
    price:            Optional[str] = Field(default=None, max_length=50)
    mileage:          Optional[str] = Field(default=None, max_length=50)
    listing_url:      Optional[str] = Field(default=None, max_length=2048)

    # Generated content
    fb_title:         Optional[str] = Field(default=None, sa_column=Column(Text))
    fb_description:   Optional[str] = Field(default=None, sa_column=Column(Text))
    fb_tags:          Optional[str] = Field(default=None, sa_column=Column(Text))  # JSON array

    # Video
    video_s3_key:     Optional[str] = Field(default=None, max_length=512)
    video_url:        Optional[str] = Field(default=None, max_length=2048)

    # Photos (JSON array of URLs)
    photo_urls:       Optional[str] = Field(default=None, sa_column=Column(Text))

    # Facebook posting status
    fb_posted:        bool = Field(default=False)
    fb_posted_at:     Optional[datetime] = Field(default=None)

    # Sold detection
    is_sold:          bool = Field(default=False)
    sold_detected_at: Optional[datetime] = Field(default=None)
    last_checked_at:  Optional[datetime] = Field(default=None)

    # Timestamps
    created_at:       datetime = Field(
        default_factory=datetime.utcnow
    )
    updated_at:       datetime = Field(
        default_factory=datetime.utcnow
    )


class ListingRead(SQLModel):
    id:             int
    user_id:        int
    job_id:         Optional[int]
    vin:            Optional[str]
    year:           Optional[str]
    make:           Optional[str]
    model:          Optional[str]
    trim:           Optional[str]
    price:          Optional[str]
    mileage:        Optional[str]
    listing_url:    Optional[str]
    fb_title:       Optional[str]
    fb_description: Optional[str]
    fb_tags:        Optional[str]
    video_s3_key:   Optional[str]
    video_url:      Optional[str]
    photo_urls:     Optional[str]
    fb_posted:      bool
    fb_posted_at:   Optional[datetime]
    is_sold:        bool
    sold_detected_at: Optional[datetime]
    last_checked_at:  Optional[datetime]
    created_at:     datetime
    updated_at:     datetime